# Generated by Django 5.2.7 on 2025-12-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransactionmodel',
            name='init_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
