# Generated by Django 5.2.7 on 2026-01-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_recurringtransactionmodel_next_run_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransactionmodel',
            name='executed_last_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
