# Generated by Django 5.2.7 on 2025-11-24 12:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_accountmodel_user'),
        ('transaction', '0002_alter_transactionmodel_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('frequency', models.CharField(choices=[('DAILY', 'Diária'), ('WEEKLY', 'Semanal'), ('BIWEEKLY', 'Quinzenal'), ('MONTHLY', 'Mensal'), ('BIMONTHLY', 'Bimestral'), ('QUARTERLY', 'Trimestral'), ('SEMIANNUAL', 'Semestral'), ('ANNUAL', 'Anual')], max_length=50)),
                ('next_run_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_transaction', to='account.accountmodel')),
            ],
            options={
                'verbose_name': 'Transação Recorrente',
                'verbose_name_plural': 'Transações Recorrentes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='recurring_root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_transactions', to='transaction.recurringtransaction'),
        ),
    ]
