# Generated by Django 5.2.7 on 2025-12-19 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_recurringtransactionmodel_init_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringtransactionmodel',
            name='execute_first_immediately',
        ),
    ]
