# Generated by Django 5.2.7 on 2025-12-23 13:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_accountmodel_user'),
        ('category', '0002_alter_categorymodel_account_and_more'),
        ('transaction', '0003_remove_recurringtransactionmodel_execute_first_immediately'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransactionmodel',
            name='type_transaction',
            field=models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa'), ('TRANSFERENCIA', 'Tranferencia')], default=''),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='type_transaction',
            field=models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa'), ('TRANSFERENCIA', 'Tranferencia')]),
        ),
        migrations.CreateModel(
            name='TransferModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('processed', models.BooleanField(default=False)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('account_transferred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_received', to='account.accountmodel')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='category.categorymodel')),
                ('original_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_sent', to='account.accountmodel')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='category.subcategorymodel')),
            ],
            options={
                'verbose_name': 'Transferência',
                'verbose_name_plural': 'Transferências',
                'ordering': ['-created_at'],
            },
        ),
    ]
