# Generated by Django 5.2.7 on 2025-11-24 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_accountmodel_user'),
        ('transaction', '0003_recurringtransaction_transactionmodel_recurring_root'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecurringTransaction',
            new_name='RecurringTransactionModel',
        ),
    ]
