# Generated by Django 5.2.7 on 2026-01-01 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_recurringtransactionmodel_executed_last_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringtransactionmodel',
            name='idempotency_key',
        ),
        migrations.RemoveField(
            model_name='recurringtransactionmodel',
            name='processed',
        ),
    ]
