# Generated by Django 5.2.7 on 2026-01-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_accountmodel_user'),
        ('category', '0002_alter_categorymodel_account_and_more'),
        ('transaction', '0004_remove_recurringtransactionmodel_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='recurringtransactionmodel',
            index=models.Index(fields=['account', 'active', '-created_at'], name='transaction_account_cbafcd_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionmodel',
            index=models.Index(fields=['-created_at'], name='transaction_created_547d1e_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionmodel',
            index=models.Index(fields=['type_transaction', '-created_at'], name='transaction_type_tr_8d54e5_idx'),
        ),
        migrations.AddIndex(
            model_name='transfermodel',
            index=models.Index(fields=['original_account', '-created_at'], name='transaction_origina_1ae2cd_idx'),
        ),
        migrations.AddIndex(
            model_name='transfermodel',
            index=models.Index(fields=['account_transferred', '-created_at'], name='transaction_account_d153ef_idx'),
        ),
    ]
