# Generated by Django 5.2.7 on 2025-12-25 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_alter_recurringtransactionmodel_type_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='transfer_root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_transactions', to='transaction.transfermodel'),
        ),
    ]
