# Generated by Django 5.2.7 on 2025-11-24 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_accountmodel_user'),
        ('category', '0002_alter_categorymodel_account_and_more'),
        ('transaction', '0004_rename_recurringtransaction_recurringtransactionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransactionmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_transactions', to='category.categorymodel'),
        ),
        migrations.AddField(
            model_name='recurringtransactionmodel',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_transactions', to='category.subcategorymodel'),
        ),
        migrations.AddField(
            model_name='recurringtransactionmodel',
            name='type_transaction',
            field=models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], default=''),
        ),
        migrations.AlterField(
            model_name='recurringtransactionmodel',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_transactions', to='account.accountmodel'),
        ),
    ]
