# Generated by Django 5.2.7 on 2026-02-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_recurringtransactionmodel_transaction_account_cbafcd_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransactionmodel',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
