# Generated by Django 5.2.7 on 2025-11-24 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_recurringtransactionmodel_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransactionmodel',
            name='init_date',
            field=models.DateField(default=datetime.date(2025, 11, 24)),
        ),
    ]
