# Generated by Django 5.2.7 on 2025-11-24 13:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_recurringtransactionmodel_init_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransactionmodel',
            name='init_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
