# Generated by Django 5.2.7 on 2025-11-24 13:45

import apps.transaction.models.recurring_transaction_model
from django.db import migrations, models
from django.utils.timezone import now


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_alter_recurringtransactionmodel_init_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransactionmodel',
            name='init_date',
            field=models.DateField(default=now),
        ),
    ]
