# Generated by Django 5.2.7 on 2025-11-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_alter_recurringtransactionmodel_init_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransactionmodel',
            name='executed_first_time',
            field=models.BooleanField(default=False),
        ),
    ]
