# Generated by Django 5.2.7 on 2025-11-28 01:26

import apps.transaction.models.recurring_transaction_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_recurringtransactionmodel_executed_first_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransactionmodel',
            name='init_date',
            field=models.DateTimeField(default=apps.transaction.models.recurring_transaction_model.default_datetime),
        ),
        migrations.AlterField(
            model_name='recurringtransactionmodel',
            name='next_run_date',
            field=models.DateTimeField(),
        ),
    ]
