# Generated by Django 5.2.7 on 2025-11-03 12:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('bank', models.CharField(choices=[('ITAÚ', 'Itaú'), ('BRADESCO', 'Bradesco'), ('SANTANDER', 'Santander'), ('CAIXA', 'Caixa Econômica Federal'), ('BANCO_DO_BRASIL', 'Banco do Brasil'), ('SAFRA', 'Banco Safra'), ('BTG_PACTUAL', 'BTG Pactual'), ('BANRISUL', 'Banrisul'), ('SICREDI', 'Sicredi'), ('SICOOB', 'Sicoob'), ('MERCANTIL_DO_BRASIL', 'Mercantil do Brasil'), ('BANCO_PAN', 'Banco PAN'), ('BANCO_ORIGINAL', 'Banco Original'), ('C6_BANK', 'C6 Bank'), ('INTER', 'Banco Inter'), ('NUBANK', 'Nubank'), ('NEON', 'Neon'), ('PAGBANK', 'PagBank'), ('BS2', 'Banco BS2'), ('WILLBANK', 'Will Bank'), ('NEXT', 'Next'), ('MEUBMG', 'Meu BMG'), ('AGIBANK', 'Agibank'), ('XP', 'XP Investimentos'), ('CREDICOAMO', 'Credicoamo'), ('CITIBANK', 'Citibank'), ('HSBC', 'HSBC'), ('JP_MORGAN', 'J.P. Morgan'), ('MORGAN_STANLEY', 'Morgan Stanley'), ('DEUTSCHE_BANK', 'Deutsche Bank'), ('BARCLAYS', 'Barclays'), ('OUTRO', 'Outro')], default='OUTRO', max_length=30)),
                ('type_account', models.CharField(choices=[('CORRENTE', 'Conta Corrente'), ('POUPANÇA', 'Conta Poupança'), ('INVESTIMENTO', 'Conta Investimento'), ('DINHEIRO', 'Dinheiro (carteira)'), ('CARTÃO', 'Cartão de Crédito')], default='CORRENTE', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'ordering': ['-created_at'],
            },
        ),
    ]
